config/routes.rb
Rails.application.routes.draw do
  
  
  devise_for :admin,controllers:{
sessions: "admin/sessions"
  }
  devise_for :customer,controllers:{
   registrations: "public/registrations",
   sessions: 'public/sessions'
  }
  
  namespace :admin do
    root to: 'homes#top'
    resources :orders,only:[:index,:show,:update]
    resources :order_details,only:[:update]
    resources :customers,only:[:index,:show,:edit,:update]
    resources :genres,only:[:index,:edit,:create,:update]
    resources :items,only:[:index,:new,:show,:edit,:create,:update]
  end
  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    resources :addresses,only:[:index,:edit,:create,:update,:destroy]
    get 'orders/complete'
    post 'orders/confirm'
    resources :orders,only:[:new,:index,:show,:create]
    resources :cart_items do
     collection do
          delete 'destroy_all'
        end
    end
    resources :cart_items,only:[:index,:create,:update,:destroy]
    get 'customers/unsubscribe'
    patch '/customers/withdraw'
    get 'customers/mypage' => 'customers#show'
    resources :customers,only:[:edit,:update]
    resources :items,only:[:index,:show]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  
  belongs_to :genre
  
  has_many :cart_items,dependent: :destroy
  has_many :order_details,dependent: :destroy
  
  enum is_active: { sale: true, stop: false }
  
  def zeikomi
    (price * 1.10).round(0)
  end
  
  def goukei
    (zeikomi + 800)
  end
  
  
  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
  
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @items = Item.page(params[:page])
  end
  
  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_items_path
  end

  def new
   @item = Item.new
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end
  
  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_items_path
  end
  
  private
  def item_params
    params.require(:item).permit(:name,:introduction,:genre_id,:price,:is_active,:image)
  end
  
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <h5 class="d-inline-block bg-light my-5 px-3">商品一覧</h5>
      <%= form_with model: @item,url: admin_item_path(@item),method: :patch do |f| %>
      <table class="mx-auto">
        <thead><td></td><td colspan="1"></td></thead>
        <tbody>
          <tr>
            <td class="pb-3"><%= f.label :image,"商品画像" %></td>
            <td class="pb-3"><%= f.file_field :image,accept:"image/*" %></td>
          </tr>
          <tr>
            <td class="pb-3"><%= f.label :name,"商品名" %></td>
            <td class="pb-3"><%= f.text_field :name %></td>
          </tr>
          <tr>
            <td class="pb-3"><%= f.label :introduction,"商品説明" %></td>
            <td class="pb-3"><%= f.text_area :introduction %></td>
          </tr>
          <tr>
            <td class="pb-3"><%= f.label :genre_id,"ジャンル" %></td>
            <td class="pb-3"><%= f.select :genre_id,options_from_collection_for_select(Genre.all,:id,:name),{include_blank: '選択してください'}%></td>
          </tr>
          <tr>
            <td class="pb-3"><%= f.label :is_active,"販売ステータス" %></td>
            <td class="pb-3">
              <%= f.radio_button :is_active,"sale" %>
              <%= f.label :is_active,"販売中" %>
              <%= f.radio_button :is_active,"stop" %>
              <%= f.label :is_active,"販売停止中"%>
            </td>
          </tr>
          <tr>
            <td></td>
            <td><%= f.submit"変更を保存",class:"btn btn-success px-3" %></td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <h5 class="d-inline-block bg-light mt-2 px-3">商品一覧</h5>
      <%= link_to new_admin_item_path,class:"d-block text-right " do %>
      <i class="fa-solid fa-circle-plus h4 text-dark"></i>
      <% end %>
      <table class="table">
        <thead class="bg-light">
          <tr>
            <th>商品ID</th>
            <th>商品名</th>
            <th>税抜価格</th>
            <th>ジャンル</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <% @items.each do |item| %>
        <tbody>
          <tr>
            <td><%= item.id %></td>
            <td>
              <%= link_to admin_item_path(item),class:"javajava " do %>
              <%= item.name %>
              <% end %>
            </td>
            <td><%= item.price.to_s(:delimited) %></td>
            <td><%= item.genre.name %></td>
            <td class="font-weight-bold">
              <% if item.is_active_i18n == "販売中" %>
              <span class="text-success"><%= item.is_active_i18n %></span>
              <% else %>
              <span class="text-primary"><%= item.is_active_i18n %></span>
              <% end %>
              </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    <%= paginate @items %>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <h5 class="d-inline-block bg-light my-5 px-3">商品新規登録</h5>
      <%= form_with model: @item,url: admin_items_path,method: :post do |f| %>
      <table class="mx-auto mt-4">
        <thead><td></td><td colspan="1"></td></thead>
      <tbody>
        <tr>
        <td class="pr-5 pb-3">
      <%= f.label :image, "商品画像" %></td>
      <td class=" pb-3">
      <%= f.file_field :image,accept:"image/*" %><br></td></tr>
      <tr>
      <td class=" pb-3">
      <%= f.label :name,"商品名" %></td>
      <td class=" pb-3">
      <%= f.text_field :name %><br></td></tr>
      <tr>
      <td class=" pb-3">
      <%= f.label :introduction,"商品説明" %></td>
      <td class=" pb-3">
      <%= f.text_area :introduction %><br></td></tr>
      <tr>
      <td class=" pb-3">
      <%= f.label :genre_id,"ジャンル名" %></td>
      <td class=" pb-3">
      <%= f.select :genre_id,options_from_collection_for_select(Genre.all,:id,:name),{include_blank: '選択してください'}%>
      </td>
      </tr>
      <tr>
        <td>
          <%= f.label :price,"税抜価格" %>
        </td>
        <td>
          <%= f.text_field :price %>円
        </td>
      </tr>
      <tr>
        <td>
          <%= f.label :is_active,"販売ステータス　" %>
        </td>
        <td>
          <%= f.radio_button :is_active,"sale" %>
          <%= f.label :is_active,"販売中" %>
          <%= f.radio_button :is_active,"stop" %>
          <%= f.label :is_active,"販売停止中" %>
        </td>
      </tr>
      <td></td>
      <td class=""><%= f.submit "新規登録",class:"btn btn-success" %></td>
          
      </tbody>
      </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-2"><h5 class="d-inline-block bg-light my-5 px-3">商品詳細</h5><br></div>
    <div class="col-md-3 mt-5 pt-5 text-center">
      <%= image_tag @item.get_image,:size=>'200x200'  %>
    </div>
    <div class="col-lg-4 col-md-5 mt-5 pt-4 text-center">
      <table class="mt-2 table table-borderless">
        <tbody>
        <tr>
          <td class="pr-4">商品名</td>
          <td><%= @item.name %></td>
        </tr>
        <tr>
          <td>商品説明</td>
          <td><%= @item.introduction %></td>
        </tr>
        <tr>
          <td>ジャンル</td>
          <td><%= @item.genre.name %></td>
        </tr>
        <tr>
          <td>税込価格<br>(税抜価格)</td>
          <td><%= @item.zeikomi.to_s(:delimited) %>
          (<%= @item.price.to_s(:delimited)  %>) 円</td>
        </tr>
        <tr >
          <td>販売ステータス</td>
          <td class="font-weight-bold mt-3">
            <% if @item.is_active_i18n == "販売中" %>
              <span class="text-success"><%= @item.is_active_i18n %></span>
              <% else %>
              <span class="text-primary"><%= @item.is_active_i18n %></span>
              <% end %>
          </td>
        </tr>
        </tbody>
      </table>
      <%= link_to "編集する",edit_admin_item_path,class:"btn btn-success px-3 " %>
    </div>
  </div>
</div>