config/routes.rb
Rails.application.routes.draw do
  
  
  devise_for :admin,controllers:{
sessions: "admin/sessions"
  }
  devise_for :customer,controllers:{
   registrations: "public/registrations",
   sessions: 'public/sessions'
  }
  
  namespace :admin do
    root to: 'homes#top'
    resources :orders,only:[:index,:show,:update]
    resources :order_details,only:[:update]
    resources :customers,only:[:index,:show,:edit,:update]
    resources :genres,only:[:index,:edit,:create,:update]
    resources :items,only:[:index,:new,:show,:edit,:create,:update]
  end
  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    resources :addresses,only:[:index,:edit,:create,:update,:destroy]
    get 'orders/complete'
    post 'orders/confirm'
    resources :orders,only:[:new,:index,:show,:create]
    resources :cart_items do
     collection do
          delete 'destroy_all'
        end
    end
    resources :cart_items,only:[:index,:create,:update,:destroy]
    get 'customers/unsubscribe'
    patch '/customers/withdraw'
    get 'customers/mypage' => 'customers#show'
    resources :customers,only:[:edit,:update]
    resources :items,only:[:index,:show]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details,dependent: :destroy

  enum payment_method: {credit_card: 0, bank: 1}

  enum status: {waiting:0,confirmation:1,production:2,sending:3,arrived:4 }
  
  def excluded
   total_payment - 800
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  def index
  end
  def show
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    if params[:order][:status] == "confirmation"
      @order.order_details.update_all(making_status: 1)
    end
    redirect_to admin_order_path(@order)
  end
  private

  def order_params
    params.require(:order).permit(:customer_id,:postal_code,:address,:name,:shipping_cost,:total_payment,:payment_method,:status)
  end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <h5 class="d-inline-block bg-light mt-3 px-3">注文履歴詳細</h5>
      <table>
        <tr>
          <th class="pr-4">購入者</th>
          <td>
            <%= link_to admin_customer_path(@order.customer) do %>
            <%= @order.customer.full_name %>
            <% end %>
          </td>
        </tr>
        <tr>
          <th class="pr-4">注文日</th>
          <td><%= @order.created_at.to_s(:datetime_jp) %></td>
        </tr>
        <tr>
          <th class="pr-4">配送先</th>
          <td>〒<%= @order.postal_code %><%= @order.address %><br>
          <%= @order.name%></td>
        </tr>
        <tr>
          <th class="pr-4">支払方法</th>
          <td><%= @order.payment_method_i18n %></td>
        </tr>
        <tr>
          <th class="pr-4">注文ステータス</th>
          <td class="mt-5">
            <%= form_with model: @order,url: admin_order_path(@order),method: :patch do |f| %>
            <%= f.select :status, Order.statuses.keys.map {|k| [I18n.t("enums.order.status.#{k}"), k]},{},{class:"mt-3 mr-4"} %>
            <%= f.submit "更新",class:"btn btn-success" %>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-8">
      <table class="table">
        <thead class="bg-light my-0">
          <tr>
            <th>商品名</th>
            <th>単価(税込)</th>
            <th>数量</th>
            <th>小計</th>
            <th colspan="2">製作ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @order.order_details.each do |order| %>
          <tr>
            <td><%= order.item.name %></td>
            <td><%= order.price.to_s(:delimited) %></td>
            <td><%= order.amount %></td>
            <td><%= ((order.price)*(order.amount)).to_s(:delimited) %></td>
            <td>
              <%= form_with model: order,url: admin_order_detail_path(order),method: :patch do |f| %>
              <%= f.select :making_status, OrderDetail.making_statuses.keys.map {|k| [I18n.t("enums.order_detail.making_status.#{k}"), k]},{},{class:"mr-4"} %>
              <%= f.submit "更新",class:"btn btn-success btn-sm" %>
              <% end %>
            </td>
            <% end %>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="col-4 mt-5 pt-5 pl-5">
      <table>
        <tr>
          <td class="font-weight-bold pr-3">商品合計</td>
          <td><%= ((@order.total_payment) - (800)).to_s(:delimited) %>円</td>
        </tr>
        <tr>
          <td class="font-weight-bold pr-3">送料</td>
          <td>800円</td>
        </tr>
        <tr>
          <th class="pr-3">請求金額合計</th>
          <th><%= @order.total_payment.to_s(:delimited) %>円</th>
        </tr>
      </table>
    </div>
  </div>
</div>