config/routes.rb
Rails.application.routes.draw do
  
  
  devise_for :admin,controllers:{
sessions: "admin/sessions"
  }
  devise_for :customer,controllers:{
   registrations: "public/registrations",
   sessions: 'public/sessions'
  }
  
  namespace :admin do
    root to: 'homes#top'
    resources :orders,only:[:index,:show,:update]
    resources :order_details,only:[:update]
    resources :customers,only:[:index,:show,:edit,:update]
    resources :genres,only:[:index,:edit,:create,:update]
    resources :items,only:[:index,:new,:show,:edit,:create,:update]
  end
  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    resources :addresses,only:[:index,:edit,:create,:update,:destroy]
    get 'orders/complete'
    post 'orders/confirm'
    resources :orders,only:[:new,:index,:show,:create]
    resources :cart_items do
     collection do
          delete 'destroy_all'
        end
    end
    resources :cart_items,only:[:index,:create,:update,:destroy]
    get 'customers/unsubscribe'
    patch '/customers/withdraw'
    get 'customers/mypage' => 'customers#show'
    resources :customers,only:[:edit,:update]
    resources :items,only:[:index,:show]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :genres,dependent: :destroy
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
    before_action :authenticate_admin!
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to '/admin/genres'
  end

  def edit
    @genre = Genre.find(params[:id])
  end


  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to '/admin/genres'
  end
end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <h5 class="d-inline-block bg-light my-3 px-3">ジャンル一覧・追加</h5>
      <%= form_with model: @genre,url: admin_genre_path(@genre),method: :patch do |f| %>
      <%= f.text_field :name %>
      <%= f.submit "変更を保存" ,class:"btn btn-success btn-sm" %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <h5 class="d-inline-block bg-light my-5 px-3">ジャンル一覧・追加</h5>
      <%= form_with model:@genre,url: admin_genres_path,method: :post do |f| %>
      <%= f.label :name,"ジャンル名",class:"mr-4 font-weight-bold" %>
      <%= f.text_field :name,class:"mr-5" %>
      <%= f.submit "新規登録",class:"btn btn-success" %>
      <% end %>
    </div>
  </div>
  <div class="row mt-5">
    <div class="col-5">
      <table class="table ">
        <thead class="bg-light">
          <td class="pr-0 pl-5 font-weight-bold">ジャンル</td>
        <td colspan=""></td>
        </thead>
      <% @genres.each do |genre| %>
        <tbody>
          <td class="">
           <%= genre.name %> 
          </td>
          <td class="pl-0">
            <%= link_to "編集する",edit_admin_genre_path(genre) ,class:"btn btn-success" %>
          </td>
      <% end %>
        </tbody>
      </table>
      
    </div>
  </div>
</div>