config/routes.rb
Rails.application.routes.draw do
  
  
  devise_for :admin,controllers:{
sessions: "admin/sessions"
  }
  devise_for :customer,controllers:{
   registrations: "public/registrations",
   sessions: 'public/sessions'
  }
  
  namespace :admin do
    root to: 'homes#top'
    resources :orders,only:[:index,:show,:update]
    resources :order_details,only:[:update]
    resources :customers,only:[:index,:show,:edit,:update]
    resources :genres,only:[:index,:edit,:create,:update]
    resources :items,only:[:index,:new,:show,:edit,:create,:update]
  end
  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    resources :addresses,only:[:index,:edit,:create,:update,:destroy]
    get 'orders/complete'
    post 'orders/confirm'
    resources :orders,only:[:new,:index,:show,:create]
    resources :cart_items do
     collection do
          delete 'destroy_all'
        end
    end
    resources :cart_items,only:[:index,:create,:update,:destroy]
    get 'customers/unsubscribe'
    patch '/customers/withdraw'
    get 'customers/mypage' => 'customers#show'
    resources :customers,only:[:edit,:update]
    resources :items,only:[:index,:show]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  def address_display
   '〒' + postal_code + ' ' + address + ' ' + name
  end
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  
  def subtotal
    item.zeikomi * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_one_attached :image
         
         has_many :addresses,dependent: :destroy
         has_many :cart_items,dependent: :destroy
         has_many :orders,dependent: :destroy
         
         
         enum is_deleted: { withdrawal: true, valider: false }
         
         def full_name
           first_name + " " + last_name
         end
         
         def full_name_kana
            first_name_kana + " " + last_name_kana
         end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :genres,dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  
  belongs_to :genre
  
  has_many :cart_items,dependent: :destroy
  has_many :order_details,dependent: :destroy
  
  enum is_active: { sale: true, stop: false }
  
  def zeikomi
    (price * 1.10).round(0)
  end
  
  def goukei
    (zeikomi + 800)
  end
  
  
  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
  
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details,dependent: :destroy

  enum payment_method: {credit_card: 0, bank: 1}

  enum status: {waiting:0,confirmation:1,production:2,sending:3,arrived:4 }
  
  def excluded
   total_payment - 800
  end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  
  enum making_status: { impossible:0,waiting:1,production:2,finish:3}
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
    before_action :authenticate_admin!
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to '/admin/genres'
  end

  def edit
    @genre = Genre.find(params[:id])
  end


  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to '/admin/genres'
  end
end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
  @orders = Order.all
  @total = 0
  end
  
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @items = Item.page(params[:page])
  end
  
  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_items_path
  end

  def new
   @item = Item.new
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end
  
  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_items_path
  end
  
  private
  def item_params
    params.require(:item).permit(:name,:introduction,:genre_id,:price,:is_active,:image)
  end
  
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  def index
  end
  def show
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    if params[:order][:status] == "confirmation"
      @order.order_details.update_all(making_status: 1)
    end
    redirect_to admin_order_path(@order)
  end
  private

  def order_params
    params.require(:order).permit(:customer_id,:postal_code,:address,:name,:shipping_cost,:total_payment,:payment_method,:status)
  end

end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name,:last_name,:first_name_kana,:last_name_kana,:postal_code,:address,:telephone_number])
  end
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NagataCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/936e751774.js" crossorigin="anonymous"></script>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-3 h1 " href="/">Nagata Cake</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if customer_signed_in? %>
            <li class="nav-item">
              <%= link_to 'マイページ',customers_mypage_path,class:"nav-link text-dark btn btn-outline-dark" %>
            </li>
            <li class="nav-item">
              <%= link_to '商品一覧',items_path, class: 'nav-link text-dark btn btn-outline-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to 'カート', cart_items_path, class: 'nav-link text-dark btn btn-outline-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'nav-link text-dark btn btn-outline-dark' %>
            </li>
            <% elsif admin_signed_in? %>
            <li>
              <%= link_to "商品一覧",admin_items_path, class: 'nav-link text-dark btn btn-outline-dark' %>
            </li>
            <li>
              <%= link_to"会員一覧",admin_customers_path, class: 'nav-link text-dark btn btn-outline-dark' %>
            </li>
            <li>
              <%= link_to "注文履歴一覧",admin_root_path, class: 'nav-link text-dark btn btn-outline-dark' %>
            </li>
            <li>
              <%= link_to "ジャンル一覧",admin_genres_path, class: 'nav-link text-dark btn btn-outline-dark' %>
            </li>
            <li>
              <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-dark btn btn-outline-dark' %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to "About",about_path,class:"nav-link text-dark btn btn-outline-dark" %>
            </li>
            <li class="nav-item">
              <%= link_to "商品一覧",items_path,class:"nav-link text-dark btn btn-outline-dark" %>
            </li>
            <li class="nav-item">
              <%= link_to "新規登録", new_customer_registration_path, class: 'nav-link text-dark btn btn-outline-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", new_customer_session_path, class: 'nav-link text-dark btn btn-outline-dark' %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
    <%= yield %>
    </main>
    <footer class="bg-dark text-white pt-5 pb-4">
      <div class="container">
        <div class="row no-gutters">
          <div class="col-12">
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>